AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sec-as-json

  Sample SAM Template for sec-as-json

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  GemsAndLibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: gems-and-lib
      Description: Layer of Bundled Gems and Lib Directory
      ContentUri: layer/gems_and_lib
      CompatibleRuntimes:
      - ruby2.7
      RetentionPolicy: Delete

  SeedCompanyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: seed_company/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Layers:
      - !Ref GemsAndLibLayer
      Environment:
        Variables:
          LAMBDA_ENV: production
      Events:
        SeedCompany:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /company/seed
            Method: post
      Policies:
        - AmazonDynamoDBFullAccess
        - SSMParameterReadPolicy:
            ParameterName: sec-as-json/dev/REPORTED_FILINGS_TOPIC
        - SSMParameterReadPolicy:
            ParameterName: sec_graph/dev/SEC_GRAPH_API_KEY
        - SSMParameterReadPolicy:
            ParameterName: sec_graph/dev/SEC_GRAPH_URL

  GetCompanyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get_company/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Layers:
      - !Ref GemsAndLibLayer
      Environment:
        Variables:
          LAMBDA_ENV: production
      Events:
        GetCompanyByCik:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /company/{cik}
            Method: get
        GetCompanyByTicker:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /company/ticker/{ticker}
            Method: get
      Policies:
      - AmazonDynamoDBFullAccess
      - SSMParameterReadPolicy:
          ParameterName: sec-as-json/dev/REPORTED_FILINGS_TOPIC
      - SSMParameterReadPolicy:
          ParameterName: sec_graph/dev/SEC_GRAPH_API_KEY
      - SSMParameterReadPolicy:
          ParameterName: sec_graph/dev/SEC_GRAPH_URL

  SeedHedgeFundsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: seed_hedge_funds/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Layers:
      - !Ref GemsAndLibLayer
      Environment:
        Variables:
          LAMBDA_ENV: production
      Policies:
      - AmazonDynamoDBFullAccess
      - SSMParameterReadPolicy:
          ParameterName: sec-as-json/dev/REPORTED_FILINGS_TOPIC
      - SSMParameterReadPolicy:
          ParameterName: sec_graph/dev/SEC_GRAPH_API_KEY
      - SSMParameterReadPolicy:
          ParameterName: sec_graph/dev/SEC_GRAPH_URL

  FilingsNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SEC Filing Notifications
      TopicName: FilingsNotificationTopic

  FeederFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: feeder/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Timeout: 180
      Layers:
      - !Ref GemsAndLibLayer
      Environment:
        Variables:
          LAMBDA_ENV: production
      Events:
        RunFeederEveryFiveMinutesEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Policies:
      - AmazonDynamoDBFullAccess
      - SNSPublishMessagePolicy:
          TopicName: FilingsNotificationTopic
      - SSMParameterReadPolicy:
          ParameterName: sec-as-json/dev/REPORTED_FILINGS_TOPIC
      - SSMParameterReadPolicy:
          ParameterName: sec_graph/dev/SEC_GRAPH_API_KEY
      - SSMParameterReadPolicy:
          ParameterName: sec_graph/dev/SEC_GRAPH_URL

  FilingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: filings
      AttributeDefinitions:
        - AttributeName: cik
          AttributeType: S
        - AttributeName: metadata
          AttributeType: S
      KeySchema:
        - AttributeName: cik
          KeyType: HASH
        - AttributeName: metadata
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Seed Company function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SeedCompanyFunction:
    Description: "Seed Company Lambda Function ARN"
    Value: !GetAtt SeedCompanyFunction.Arn
  SeedCompanyFunctionIamRole:
    Description: "Implicit IAM Role created for Seed Company function"
    Value: !GetAtt SeedCompanyFunction.Arn
